name: "GameLib"
version: "1.0"
main: "com.pythoncraft.gamelib.GameLib"
api-version: "1.21"
authors: [pythoncraft]
description: "A library for game development in Minecraft"
version: 1.0
api-version: 1.20